import { type NextPage } from "next";
import Head from "next/head";
import { MapProvider } from "react-map-gl";
import { MapboxMap } from "../components/map/MapboxMap";
import { MapControls } from "../components/map/MapControls";

// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen">
        <MapProvider>
          <div className="absolute right-4 top-4 z-50">
            <MapControls />
          </div>
          <MapboxMap />
        </MapProvider>
      </div>
    </>
  );
};

export default Home;
